export const logos = [
  {
    name: "Logo 1",
    src: "/logo/logo-1.webp",
    alt: "Logo 1",
    desc: "Decentralized finance (DeFi) platform logo, empowering global financial inclusion.",
  },
  {
    name: "Logo 2",
    src: "/logo/logo-2.webp",
    alt: "Logo 2",
    desc: "NFT marketplace logo, revolutionizing digital art ownership and trading.",
  },
  {
    name: "Logo 3",
    src: "/logo/logo-3.webp",
    alt: "Logo 3",
    desc: "Blockchain gaming logo, creating immersive experiences with token rewards.",
  },
  {
    name: "Logo 4",
    src: "/logo/logo-4.webp",
    alt: "Logo 4",
    desc: "DAO governance platform logo, enabling decentralized decision-making.",
  },
  {
    name: "Logo 5",
    src: "/logo/logo-5.webp",
    alt: "Logo 5",
    desc: "Crypto wallet logo, securing digital assets with blockchain technology.",
  },
  {
    name: "Logo 6",
    src: "/logo/logo-6.webp",
    alt: "Logo 6",
    desc: "Blockchain identity logo, ensuring privacy and security in digital identities.",
  },
  {
    name: "Logo 7",
    src: "/logo/logo-7.webp",
    alt: "Logo 7",
    desc: "Smart contract auditing logo, ensuring code reliability and security.",
  },
  {
    name: "Logo 8",
    src: "/logo/logo-8.webp",
    alt: "Logo 8",
    desc: "Blockchain analytics logo, providing insights into decentralized networks.",
  },
  {
    name: "Logo 9",
    src: "/logo/logo-9.webp",
    alt: "Logo 9",
    desc: "Decentralized exchange (DEX) logo, enabling peer-to-peer cryptocurrency trading.",
  },
  {
    name: "Logo 10",
    src: "/logo/logo-10.webp",
    alt: "Logo 10",
    desc: "Tokenized real estate logo, digitizing property ownership on the blockchain.",
  },
  {
    name: "Logo 11",
    src: "/logo/logo-11.webp",
    alt: "Logo 11",
    desc: "Blockchain-based voting system logo, ensuring transparent and secure elections.",
  },
  {
    name: "Logo 12",
    src: "/logo/logo-12.webp",
    alt: "Logo 12",
    desc: "Decentralized social media platform logo, fostering censorship-resistant communication.",
  },
  {
    name: "Logo 13",
    src: "/logo/logo-13.webp",
    alt: "Logo 13",
    desc: "Blockchain supply chain management logo, enhancing transparency and efficiency.",
  },
  {
    name: "Logo 14",
    src: "/logo/logo-14.webp",
    alt: "Logo 14",
    desc: "Cross-chain interoperability logo, enabling seamless interaction between blockchain networks.",
  },
  {
    name: "Logo 5",
    src: "/logo/logo-5.webp",
    alt: "Logo 5",
    desc: "Crypto wallet logo, securing digital assets with blockchain technology.",
  },
  {
    name: "Logo 6",
    src: "/logo/logo-6.webp",
    alt: "Logo 6",
    desc: "Blockchain identity logo, ensuring privacy and security in digital identities.",
  },
  {
    name: "Logo 7",
    src: "/logo/logo-7.webp",
    alt: "Logo 7",
    desc: "Smart contract auditing logo, ensuring code reliability and security.",
  },
  {
    name: "Logo 8",
    src: "/logo/logo-8.webp",
    alt: "Logo 8",
    desc: "Blockchain analytics logo, providing insights into decentralized networks.",
  },
  {
    name: "Logo 9",
    src: "/logo/logo-9.webp",
    alt: "Logo 9",
    desc: "Decentralized exchange (DEX) logo, enabling peer-to-peer cryptocurrency trading.",
  },
  {
    name: "Logo 10",
    src: "/logo/logo-10.webp",
    alt: "Logo 10",
    desc: "Tokenized real estate logo, digitizing property ownership on the blockchain.",
  },
  {
    name: "Logo 11",
    src: "/logo/logo-11.webp",
    alt: "Logo 11",
    desc: "Blockchain-based voting system logo, ensuring transparent and secure elections.",
  },
  {
    name: "Logo 12",
    src: "/logo/logo-12.webp",
    alt: "Logo 12",
    desc: "Decentralized social media platform logo, fostering censorship-resistant communication.",
  },
  {
    name: "Logo 13",
    src: "/logo/logo-13.webp",
    alt: "Logo 13",
    desc: "Blockchain supply chain management logo, enhancing transparency and efficiency.",
  },
  {
    name: "Logo 14",
    src: "/logo/logo-14.webp",
    alt: "Logo 14",
    desc: "Cross-chain interoperability logo, enabling seamless interaction between blockchain networks.",
  },
  {
    name: "Logo 5",
    src: "/logo/logo-5.webp",
    alt: "Logo 5",
    desc: "Crypto wallet logo, securing digital assets with blockchain technology.",
  },
  {
    name: "Logo 6",
    src: "/logo/logo-6.webp",
    alt: "Logo 6",
    desc: "Blockchain identity logo, ensuring privacy and security in digital identities.",
  },
  {
    name: "Logo 7",
    src: "/logo/logo-7.webp",
    alt: "Logo 7",
    desc: "Smart contract auditing logo, ensuring code reliability and security.",
  },
  {
    name: "Logo 8",
    src: "/logo/logo-8.webp",
    alt: "Logo 8",
    desc: "Blockchain analytics logo, providing insights into decentralized networks.",
  },
  {
    name: "Logo 9",
    src: "/logo/logo-9.webp",
    alt: "Logo 9",
    desc: "Decentralized exchange (DEX) logo, enabling peer-to-peer cryptocurrency trading.",
  },
  {
    name: "Logo 10",
    src: "/logo/logo-10.webp",
    alt: "Logo 10",
    desc: "Tokenized real estate logo, digitizing property ownership on the blockchain.",
  },
  {
    name: "Logo 11",
    src: "/logo/logo-11.webp",
    alt: "Logo 11",
    desc: "Blockchain-based voting system logo, ensuring transparent and secure elections.",
  },
  {
    name: "Logo 12",
    src: "/logo/logo-12.webp",
    alt: "Logo 12",
    desc: "Decentralized social media platform logo, fostering censorship-resistant communication.",
  },
  {
    name: "Logo 13",
    src: "/logo/logo-13.webp",
    alt: "Logo 13",
    desc: "Blockchain supply chain management logo, enhancing transparency and efficiency.",
  },
  {
    name: "Logo 14",
    src: "/logo/logo-14.webp",
    alt: "Logo 14",
    desc: "Cross-chain interoperability logo, enabling seamless interaction between blockchain networks.",
  },
  {
    name: "Logo 5",
    src: "/logo/logo-5.webp",
    alt: "Logo 5",
    desc: "Crypto wallet logo, securing digital assets with blockchain technology.",
  },
  {
    name: "Logo 6",
    src: "/logo/logo-6.webp",
    alt: "Logo 6",
    desc: "Blockchain identity logo, ensuring privacy and security in digital identities.",
  },
  {
    name: "Logo 7",
    src: "/logo/logo-7.webp",
    alt: "Logo 7",
    desc: "Smart contract auditing logo, ensuring code reliability and security.",
  },
  {
    name: "Logo 8",
    src: "/logo/logo-8.webp",
    alt: "Logo 8",
    desc: "Blockchain analytics logo, providing insights into decentralized networks.",
  },
  {
    name: "Logo 9",
    src: "/logo/logo-9.webp",
    alt: "Logo 9",
    desc: "Decentralized exchange (DEX) logo, enabling peer-to-peer cryptocurrency trading.",
  },
  {
    name: "Logo 10",
    src: "/logo/logo-10.webp",
    alt: "Logo 10",
    desc: "Tokenized real estate logo, digitizing property ownership on the blockchain.",
  },
  {
    name: "Logo 11",
    src: "/logo/logo-11.webp",
    alt: "Logo 11",
    desc: "Blockchain-based voting system logo, ensuring transparent and secure elections.",
  },
  {
    name: "Logo 12",
    src: "/logo/logo-12.webp",
    alt: "Logo 12",
    desc: "Decentralized social media platform logo, fostering censorship-resistant communication.",
  },
  {
    name: "Logo 13",
    src: "/logo/logo-13.webp",
    alt: "Logo 13",
    desc: "Blockchain supply chain management logo, enhancing transparency and efficiency.",
  },
  {
    name: "Logo 14",
    src: "/logo/logo-14.webp",
    alt: "Logo 14",
    desc: "Cross-chain interoperability logo, enabling seamless interaction between blockchain networks.",
  },

  // Continue with more logos...
];
